### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by CRC32EX** [mavenlin/wrap_dll#10]
Export source code is successfully working.
But, can't compile source code well.

This dll's function name includes `@16`.
This is problem, i think.
Could you fix it?

![image](https://user-images.githubusercontent.com/25629617/107874862-ed301800-6eff-11eb-9026-1958e0b3b6fc.png)

[Exforce.zip](https://github.com/mavenlin/wrap_dll/files/5977587/Exforce.zip)

# My Environment
|||
|:--|:--|
|OS|Windows 10 64bit Pro 20H2|
|Visual Studio|Visual Studio 2019 Community|
|Windows SDK Version|10.0.19041.0|
|Platform Toolset|Visual Studio 2019 (v142)|

**Comment by mavenlin** [comment]
Could you paste the compilation error message so I can help you?
I don't have a windows machine at hand to test.

**Comment by CRC32EX** [comment]
[Exforce.zip](https://github.com/mavenlin/wrap_dll/files/5993561/Exforce.zip)
[image.png](https://user-images.githubusercontent.com/25629617/108163108-cc4f0900-7131-11eb-9c84-dc748618a860.png)
[error.txt](https://github.com/mavenlin/wrap_dll/files/5993547/error.txt)

**Comment by CRC32EX** [comment]
I found solution.
https://github.com/kagasu/ProxyDllGenerator
